//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CfgDoc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CfgDoc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a {
        ///	background-color:#fff;
        ///	color:#00f;
        ///	text-decoration:none;
        ///}
        ///a:hover {
        ///	background-color:#fff;
        ///	color:#c00;
        ///	text-decoration:underline;
        ///}
        ///blockquote {
        ///	margin-left: 48;
        ///}
        ///h1 {
        ///	background-color: rgb(33,85,132);
        ///	border: 1 solid black;
        ///	color: white;
        ///	font: 12pt Arial Black;
        ///	padding-left: 2pt;
        ///}
        ///h2 {
        ///	background-color: white;
        ///	color: black;
        ///	font: 12pt Arial Black;
        ///	padding-left: 2pt;
        ///}
        ///h3 {
        ///	background-color: white;
        ///	color: black;
        ///	font: 11pt Arial Black;
        ///	padding-left: 4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string css {
            get {
                return ResourceManager.GetString("css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///	&lt;td width=&quot;40%&quot; class=&quot;$class&quot; nowrap&gt;$host_name ($host_dbid)&lt;/td&gt;
        ///	&lt;td width=&quot;25%&quot; class=&quot;$class&quot; nowrap&gt;$host_os_type $host_os_version&lt;/td&gt;
        ///	&lt;td width=&quot;20%&quot; class=&quot;$class&quot; nowrap&gt;$host_ip_address&lt;/td&gt;
        ///	&lt;td width=&quot;15%&quot; class=&quot;$class&quot; nowrap&gt;$host_lca_port&lt;/td&gt;
        ///&lt;/tr&gt;
        ///.
        /// </summary>
        internal static string host {
            get {
                return ResourceManager.GetString("host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/table&gt;.
        /// </summary>
        internal static string host_end {
            get {
                return ResourceManager.GetString("host_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 id=\&quot;Hosts\&quot;&gt;Hosts&lt;/h2&gt;
        ///&lt;table cellpadding=5 cellspacing=0 border=0&gt;
        ///&lt;tr&gt;&lt;th&gt;Name (DBID)&lt;/th&gt;&lt;th&gt;OS&lt;/th&gt;&lt;th&gt;Address&lt;/th&gt;&lt;th&gt;LCA Port&lt;/th&gt;&lt;/tr&gt;
        ///.
        /// </summary>
        internal static string host_start {
            get {
                return ResourceManager.GetString("host_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/body&gt;
        ///&lt;/html&gt;
        ///.
        /// </summary>
        internal static string html_end {
            get {
                return ResourceManager.GetString("html_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;META http-equiv=Content-Type content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;./gencfg.css&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;center style=&quot;font:20pt Arial Black&quot;&gt;Genesys CTI Framework&lt;br&gt;
        ///System Documentation&lt;/center&gt;
        ///&lt;p align=&quot;center&quot;&gt;for&lt;/p&gt;
        ///&lt;center style=&quot;font:20pt Arial Black&quot;&gt;$Company&lt;/center&gt;
        ///&lt;center&gt;
        ///&lt;p style=&quot;font:16pt Arial&quot;&gt;$Description&lt;/p&gt;
        ///&lt;p&gt;prepared by&lt;br&gt;
        ///$Author&lt;br&gt;
        ///Genesys Professional Services&lt;br&gt;
        ///Genesys&amp;reg; Telecommunications Laboratories, In [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string html_start {
            get {
                return ResourceManager.GetString("html_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 id=\&quot;Solutions\&quot;&gt;Solutions&lt;/h2&gt;.
        /// </summary>
        internal static string solution_start {
            get {
                return ResourceManager.GetString("solution_start", resourceCulture);
            }
        }
        
        internal static byte[] WordRunBookTemplate {
            get {
                object obj = ResourceManager.GetObject("WordRunBookTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
